/** Minimal HansomeGame ABI for Commit / Reveal / finalizeDay + creditBatch (Season 1). */
export const hansomeGameAbi = [
  { type: "error", name: "WrongPhase", inputs: [] },
  { type: "error", name: "AlreadyCommitted", inputs: [] },
  { type: "error", name: "AlreadyRevealed", inputs: [] },
  { type: "error", name: "NotCommitted", inputs: [] },
  { type: "error", name: "BadCommitHash", inputs: [] },
  { type: "error", name: "IllegalLocation", inputs: [] },
  { type: "error", name: "NotAuthorized", inputs: [] },
  { type: "error", name: "TokenNotRevealed", inputs: [] },
  { type: "error", name: "InvalidSide", inputs: [] },
  { type: "error", name: "AlreadySettled", inputs: [] },
  { type: "error", name: "AlreadyFinalized", inputs: [] },
  { type: "error", name: "NotFinalized", inputs: [] },
  { type: "error", name: "SeedMissing", inputs: [] },
  { type: "error", name: "SafeMode", inputs: [] },
  { type: "error", name: "CommitGloballyPaused", inputs: [] },
  { type: "error", name: "InsufficientTreasury", inputs: [] },
  { type: "error", name: "InvalidDayTiming", inputs: [] },
  { type: "error", name: "TestnetUnlockForbidden", inputs: [] },
  { type: "error", name: "BadTestnetIdentities", inputs: [] },
  { type: "error", name: "LengthMismatch", inputs: [] },
  { type: "error", name: "BatchTooLarge", inputs: [] },
  {
    type: "function",
    name: "commit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "day", type: "uint256" },
      { name: "commitHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "reveal",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "day", type: "uint256" },
      { name: "locationId", type: "uint8" },
      { name: "salt", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "testnetRelayerRevealBatch",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenIds", type: "uint256[]" },
      { name: "day", type: "uint256" },
      { name: "locationIds", type: "uint8[]" },
      { name: "salts", type: "bytes32[]" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "computeCommitHash",
    stateMutability: "pure",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "day", type: "uint256" },
      { name: "locationId", type: "uint8" },
      { name: "salt", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "commitHashOf",
    stateMutability: "view",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "day", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "currentDay",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "dayState",
    stateMutability: "view",
    inputs: [{ name: "day", type: "uint256" }],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "finalizeDay",
    stateMutability: "nonpayable",
    inputs: [{ name: "day", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "creditBatch",
    stateMutability: "nonpayable",
    inputs: [
      { name: "day", type: "uint256" },
      { name: "limit", type: "uint256" },
    ],
    outputs: [{ name: "credited", type: "uint256" }],
  },
  {
    type: "function",
    name: "settleDay",
    stateMutability: "nonpayable",
    inputs: [{ name: "day", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "isSettled",
    stateMutability: "view",
    inputs: [{ name: "day", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "isFinalized",
    stateMutability: "view",
    inputs: [{ name: "day", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "creditProgress",
    stateMutability: "view",
    inputs: [{ name: "day", type: "uint256" }],
    outputs: [
      { name: "cursor", type: "uint256" },
      { name: "total", type: "uint256" },
      { name: "finalized", type: "bool" },
      { name: "settled", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "pendingRewardOf",
    stateMutability: "view",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "day", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "MAX_REVEAL_BATCH",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "MAX_CREDIT_BATCH",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "locationOf",
    stateMutability: "view",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "day", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "distributor",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "dayZero",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "dayLength",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "commitDuration",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "revealDuration",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "randomness",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "event",
    name: "Revealed",
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "day", type: "uint256", indexed: true },
      { name: "locationId", type: "uint8", indexed: false },
      { name: "side", type: "uint8", indexed: false },
    ],
  },
] as const;
